annotations:
  artifacthub.io/category: database
  artifacthub.io/changes: "- kind: added\n  description: Update Qdrant to v1.14.0\n-
    kind: added\n  description: Make chart test image configurable     \n  links:\n
    \   - name: Github Issue\n      url: https://github.com/qdrant/qdrant-helm/pull/320\n-
    kind: fixed\n  description: Do not unnecessarily update file system ownership
    when unprivilged image is not used \n  links:\n    - name: Github Issue\n      url:
    https://github.com/qdrant/qdrant-helm/pull/321"
apiVersion: v2
appVersion: v1.14.0
description: Qdrant - Vector Database for the next generation of AI applications.
home: https://qdrant.tech
icon: https://qdrant.github.io/qdrant-helm/logo_with_text.svg
keywords:
- vector database
maintainers:
- email: info@qdrant.com
  name: qdrant
  url: https://github.com/qdrant
name: qdrant
sources:
- https://github.com/qdrant/qdrant
- https://github.com/qdrant/qdrant-helm
type: application
version: 1.14.0
