apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-storage
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard