
name: "item_pipeline"
backend: "python"
max_batch_size: 512
input [
  { name: "items", data_type: TYPE_STRING, dims: [1] },
  { name: "categories", data_type: TYPE_STRING, dims: [-1] },
  { name: "prices", data_type: TYPE_FP32, dims: [1] },
  { name: "main_categories", data_type: TYPE_STRING, dims: [-1] },
  { name: "rating_cnt_365d", data_type: TYPE_INT64, dims: [1] },
  { name: "rating_avg_365d", data_type: TYPE_FP32, dims: [1] },
  { name: "rating_cnt_90d", data_type: TYPE_INT64, dims: [1] },
  { name: "rating_avg_90d", data_type: TYPE_FP32, dims: [1] },
  { name: "rating_cnt_30d", data_type: TYPE_INT64, dims: [1] },
  { name: "rating_avg_30d", data_type: TYPE_FP32, dims: [1] },
  { name: "rating_cnt_7d", data_type: TYPE_INT64, dims: [1] },
  { name: "rating_avg_7d", data_type: TYPE_FP32, dims: [1] }
]
output [
  { name: "item_features", data_type: TYPE_FP32, dims: [416] }
]
instance_group [ { kind: KIND_CPU, count: 4 } ]
