name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv==0.6.2
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Check style
        run: make style
      - name: Run tests
        run: make test
