apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ .Values.rbac.saName }}
      initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command:
          - sh
          - -c
          - |
            echo "Fix permissions on /var/jenkins_home"
            chown -R 1000:1000 /var/jenkins_home
        volumeMounts:
          - name: jenkins-data
            mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: {{ .Values.jenkins.image }}
        env:
          - name: JENKINS_OPTS
            value: "--prefix={{ .Values.jenkins.prefix }}"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
{{- toYaml .Values.jenkins.resources | nindent 10 }}
        ports:
          - containerPort: 8080
            name: httpport
          - containerPort: 50000
            name: jnlpport
        livenessProbe:
          httpGet:
            path: "{{ .Values.jenkins.prefix }}/login"
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: "{{ .Values.jenkins.prefix }}/login"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
          - name: jenkins-data
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
