apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageClass.name }}
  claimRef:
    name: jenkins-pv-claim
    namespace: {{ .Values.namespace }}
  capacity:
    storage: {{ .Values.jenkins.storage.pvSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.jenkins.storage.hostPath }}"
